name: vidraui
description: A clean, high-performance Flutter design system and widget library built entirely on WidgetsApp, free from Material or Cupertino dependencies.
version: 0.0.1
homepage: https://github.com/heyvidra/VidraUI
repository: https://github.com/heyvidra/VidraUI
issue_tracker: https://github.com/heyvidra/VidraUI/issues

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: false
