import 'docs.dart';

const vDocCatalog = <VDocPageMetadata>[
  VDocPageMetadata(
    slug: 'animated-switcher',
    category: 'Motion',
    title: 'Animated Switcher',
    zhTitle: '内容切换',
    summary:
        'Content switcher with preset or custom enter/exit animations, controller-driven with automatic slide direction.',
    symbols: [
      'VAnimatedSwitcher',
      'VAnimatedSwitcherController',
      'VContentTransition',
      'VTransitionBuilder',
    ],
    snippetIds: [],
    usageNotes: [
      'Use a VAnimatedSwitcherController to manage child index and auto-detect direction.',
      'Pre-built transitions: fade, slide (auto-inferred direction), scaleFade.',
      'Customise via enterTransition / exitTransition builders.',
    ],
  ),
  VDocPageMetadata(
    slug: 'buttons',
    category: 'Components',
    title: 'Buttons',
    zhTitle: '按钮',
    summary:
        'Action controls with variants, sizes, loading state, icons, semantics, and keyboard activation.',
    symbols: [
      'VButton',
      'VButtonVariant',
      'VControlSize',
      'VButtonShape',
      'VButtonTokens',
    ],
    snippetIds: ['button-variants', 'button-icon-loading'],
    usageNotes: [
      'Use primary for the main action, secondary for lower-emphasis actions, and danger only for destructive actions.',
      'Use VText for labels and VIcon for icons so color and size inherit from the button theme.',
      'Pass semanticLabel for icon-only buttons and loadingSemanticLabel when async work replaces the visible label.',
      'Use loading to block duplicate activation while work is pending instead of manually swapping widgets.',
    ],
  ),
  VDocPageMetadata(
    slug: 'chips',
    category: 'Components',
    title: 'Chips',
    zhTitle: '标签',
    summary:
        'Compact selectable, deletable, and informational tokens for filters and metadata.',
    symbols: ['VChip', 'VChipVariant', 'VControlSize', 'VChipTokens'],
    snippetIds: ['chip-variants'],
    usageNotes: [
      'Prefer soft chips for neutral metadata and filled chips for selected state.',
      'Use onDeleted only when removal is available from the same UI context.',
    ],
  ),
  VDocPageMetadata(
    slug: 'timeline',
    category: 'Feedback',
    title: 'TimeLine',
    zhTitle: '时间轴',
    summary:
        'Vertical event timeline with colored status nodes (pending, active, completed, error).',
    symbols: [
      'VTimeLine',
      'VTimeLineItem',
      'VTimeLineStatus',
      'VTimeLineTheme',
      'VTimeLineTokens',
    ],
    snippetIds: [],
    usageNotes: [
      'Status nodes auto-color from theme tokens.',
      'Completed shows ✓, error shows ✕, active is filled, pending is hollow.',
      'Last item omits the trailing line.',
    ],
  ),
  VDocPageMetadata(
    slug: 'toggles',
    category: 'Forms',
    title: 'Toggles',
    zhTitle: '选择控件',
    summary:
        'Checkbox, switch, and radio controls backed by VidraUI interaction and component tokens.',
    symbols: [
      'VCheckbox',
      'VSwitch',
      'VRadio',
      'VRadioGroup',
      'VCheckboxTheme',
      'VSwitchTheme',
      'VRadioTheme',
      'VCheckboxTokens',
      'VSwitchTokens',
      'VRadioTokens',
    ],
    snippetIds: ['toggle-controls'],
    usageNotes: [
      'Keep state outside the control and update it from onChanged/onSelected.',
      'Provide labels or semantic labels for screen reader clarity.',
    ],
  ),
  VDocPageMetadata(
    slug: 'text-field',
    category: 'Forms',
    title: 'Text Field',
    zhTitle: '文本输入',
    summary:
        'EditableText-based input with labels, hints, errors, icons, controller ownership, and accessibility semantics.',
    symbols: [
      'VTextField',
      'VTextFieldContextMenuBuilder',
      'VTextFieldContextMenuData',
      'VTextFieldContextMenuItem',
      'VTextSelectionMenu',
      'VTextSelectionMenuItem',
      'VTextSelectionMenuLayoutDelegate',
      'VInputTheme',
      'VInputTokens',
    ],
    snippetIds: ['text-field-basic', 'text-field-owned-state'],
    usageNotes: [
      'Use label for persistent identity and hint only for input examples or formatting guidance.',
      'Use errorText for field-level validation messages; it is announced as a live region.',
      'Pass an external controller/focusNode when the parent owns lifecycle, such as forms, search bars, or restoreable inputs.',
      'Use minLines/maxLines for multiline input; do not replace VTextField with Material TextField.',
    ],
  ),
  VDocPageMetadata(
    slug: 'form',
    category: 'Forms',
    title: 'Form',
    zhTitle: '表单',
    summary:
        'Simple form, field wrappers, and number stepping for collecting and presenting validation errors.',
    symbols: ['VForm', 'VFormState', 'VFormField', 'VFormFieldError', 'VNumberBox', 'VControlSize'],
    snippetIds: ['form-basic', 'form-submit'],
    usageNotes: [
      'Use VFormState.validate from a GlobalKey for simple synchronous validation.',
      'Keep business validation in app code; VidraUI only renders structure and errors.',
    ],
  ),
  VDocPageMetadata(
    slug: 'select',
    category: 'Forms',
    title: 'Select',
    zhTitle: '选择器',
    summary:
        'Single and multiple option selection without Material popup dependencies.',
    symbols: [
      'VSelect',
      'VSelectOption',
      'VSelectTheme',
      'VSelectTokens',
    ],
    snippetIds: ['select-basic'],
    usageNotes: [
      'Use VSelect.multiple when the selection model is a Set.',
      'Disable individual VSelectOption values that should remain visible but unavailable.',
    ],
  ),
  VDocPageMetadata(
    slug: 'segmented-control',
    category: 'Forms',
    title: 'Segmented Control',
    zhTitle: '分段选择器',
    summary:
        'A premium, sliding segmented horizontal selector matching macOS design patterns. Smooth active pill animation with keyboard arrow-key cycling.',
    symbols: [
      'VSegmentedControl',
      'VSegmentedControlOption',
      'VControlSize',
      'VSegmentedControlTheme',
      'VSegmentedControlTokens',
    ],
    snippetIds: ['segmented-control-basic', 'segmented-control-sizes'],
    usageNotes: [
      'Use VSegmentedControl for horizontal option selectors where all options are visible at once.',
      'Provide the T-typed value and matching VSegmentedControlOption values for type-safe selection.',
      'ArrowLeft and ArrowRight cycle between options when focused; disabled options are skipped.',
      'Use VControlSize.sm, .md, or .lg to match surrounding UI density.',
      'Disable individual options with enabled: false to keep them visible but non-selectable.',
      'Use VSegmentedControlTheme.override to restyle only VSegmentedControl in a subtree.',
    ],
  ),
  VDocPageMetadata(
    slug: 'menu',
    category: 'Overlay',
    title: 'Menu',
    zhTitle: '菜单',
    summary:
        'Anchored action and selection menus backed by VidraUI overlay and component tokens.',
    symbols: [
      'VMenuAnchor',
      'VMenuAnchorBuilder',
      'VMenuController',
      'VMenuItem',
      'VMenuSelectionMode',
      'VMenuItemRole',
      'VMenuTheme',
      'VMenuTokens',
      'VContextMenu',
      'VContextMenuItem',
      'VContextMenuStyle',
    ],
    snippetIds: ['menu-action-basic', 'menu-selection-basic'],
    usageNotes: [
      'Use VMenuAnchor for anchored action menus and lightweight selection menus.',
      'Use VMenuItem.separator to divide related action groups.',
      'Prefer VSelect when the control is a form field with a persistent value label.',
    ],
  ),
  VDocPageMetadata(
    slug: 'slider',
    category: 'Forms',
    title: 'Slider',
    zhTitle: '滑块',
    summary:
        'Token-aware numeric input for bounded continuous values with disabled state support.',
    symbols: ['VSlider', 'VSliderTokens'],
    snippetIds: ['slider-basic'],
    usageNotes: [
      'Keep values normalized unless a domain-specific scale is documented in the UI.',
    ],
  ),
  VDocPageMetadata(
    slug: 'date-time',
    category: 'Forms',
    title: 'Date & Time',
    zhTitle: '日期时间',
    summary:
        'Calendar and clock pickers for local DateTime and VTimeOfDay selection.',
    symbols: [
      'VDatePicker',
      'VDatePickerTheme',
      'VDatePickerTokens',
      'VTimePicker',
      'VTimePickerTheme',
      'VTimePickerTokens',
      'VTimeOfDay',
      'TimeOfDay',
    ],
    snippetIds: ['date-picker-basic', 'date-picker-range', 'time-picker-basic'],
    usageNotes: [
      'Store selected values in the parent and pass them back through selected.',
      'VDatePicker supports ArrowLeft and ArrowRight to move one day, ArrowUp and ArrowDown to move one week, and Enter or Space to select the focused date.',
      'VDatePicker date cells expose selected, today, and disabled semantics.',
      'VTimePicker exposes hour and minute item labels, selected semantics, and Enter or Space activation for the focused item.',
      'VTimePicker is currently 24-hour only and does not include an AM/PM period column.',
    ],
  ),
  VDocPageMetadata(
    slug: 'surface',
    category: 'Layout',
    title: 'Surface',
    zhTitle: '表面',
    summary:
        'Tokenized containers for base, elevated, card, and panel surfaces, plus elevation-aware containers.',
    symbols: [
      'VBackground',
      'VSurface',
      'VSurfaceVariant',
      'VSurfaceTheme',
      'VSurfaceTokens',
      'VSurfaceBackground',
      'VBorderStyle',
      'VElevation',
    ],
    snippetIds: [
      'surface-variants',
      'surface-background-color',
      'surface-background-gradient',
      'scaffold-background-gradient',
      'surface-elevation',
    ],
    usageNotes: [
      'Use VSurface instead of raw DecoratedBox when a tokenized container is needed.',
      'Pick the variant by semantic role, not by a one-off color.',
      'VBackground is a one-off escape hatch for page, container, and overlay surfaces.',
      'Prefer theme/component tokens and appearance for reusable styling; use background only for local one-off overrides.',
      'Strong stateful controls such as VButton, VTextField, VSelect, VTable, VDatePicker, and VTimePicker intentionally do not expose direct background props.',
      'VSurfaceBackground is a deprecated alias; use VBackground instead.',
      'Pass VElevation to VSurface to automatically resolve elevation-aware background color and box shadow.',
    ],
  ),
  VDocPageMetadata(
    slug: 'typography',
    category: 'Foundation',
    title: 'Typography',
    zhTitle: '排版',
    summary:
        'Text variants and typography tokens for consistent hierarchy and readable copy.',
    symbols: [
      'VText',
      'VSelectableText',
      'VTextVariant',
      'VTypography',
      'VRichText',
      'VTextSpan',
    ],
    snippetIds: [
      'typography-basic',
      'selectable-text-basic',
    ],
    usageNotes: [
      'Prefer VText variants over ad hoc TextStyle values.',
      'Use VSelectableText for read-only copy that users should be able to select, copy, or inspect with the platform text toolbar.',
      'Use VRichText for short styled inline spans.',
    ],
  ),
  VDocPageMetadata(
    slug: 'layout',
    category: 'Layout',
    title: 'Layout',
    zhTitle: '布局',
    summary:
        'Spacing-aware layout helpers and page shell primitives for app screens.',
    symbols: [
      'VBox',
      'VFlex',
      'VScaffold',
      'VSizes',
      'VResizable',
      'VResizeHandle',
      'VResizeHandles',
      'VResizeBoundaryBehavior',
      'VResizeHandleBuilder',
      'VResizeStartDetails',
      'VResizeUpdateDetails',
      'VResizeEndDetails',
    ],
    snippetIds: ['layout-basic'],
    usageNotes: [
      'Use gap and padding parameters to reduce repeated magic numbers.',
      'VScaffold is a custom page shell, not Flutter Material Scaffold.',
    ],
  ),
  VDocPageMetadata(
    slug: 'steps',
    category: 'Feedback',
    title: 'Steps',
    zhTitle: '步骤条',
    summary:
        'Step-by-step progress indicator with dot/number modes and horizontal/vertical layouts.',
    symbols: ['VSteps', 'VStep', 'VStepsMode', 'VStepStatus', 'VStepsTheme', 'VStepsTokens'],
    snippetIds: [],
    usageNotes: [
      'Use VStepsMode.dot for minimal dots, VStepsMode.number for numbered circles.',
      'Direction: Axis.horizontal for inline, Axis.vertical for sidebar-style.',
      'Status is auto-derived from the current index.',
    ],
  ),
  VDocPageMetadata(
    slug: 'sticky-header',
    category: 'Layout',
    title: 'Sticky Header',
    zhTitle: '吸顶头部',
    summary:
        'A zero-dependency persistent sliver header for CustomScrollView that pins to the viewport top when scrolled.',
    symbols: [
      'VStickyHeader',
      'VStickyHeaderDelegate',
    ],
    snippetIds: ['sticky-header-basic'],
    usageNotes: [
      'Use VStickyHeader inside CustomScrollView alongside other slivers.',
      'Set pinned: true to make the header stay fixed at the top of the viewport.',
      'Supports dynamic resizing: specify different minHeight and maxHeight to make headers scale down smoothly on scroll.',
    ],
  ),
  VDocPageMetadata(
    slug: 'app-bar',
    category: 'Layout',
    title: 'App Bar',
    zhTitle: '应用栏',
    summary:
        'Flat, elevated, transparent, and sliver app bars built without Material AppBar.',
    symbols: [
      'VAppBar',
      'VSliverAppBar',
      'VAppBarVariant',
      'VSliverAppBarFlexibleBuilder',
      'VAppBarTheme',
      'VAppBarTokens',
    ],
    snippetIds: ['app-bar-basic'],
    usageNotes: [
      'Use VAppBar.sliver inside CustomScrollView when the header participates in scroll.',
    ],
  ),
  VDocPageMetadata(
    slug: 'list-tile',
    category: 'Layout',
    title: 'List Tile',
    zhTitle: '列表项',
    summary:
        'Consistent row layout for leading media, title, subtitle, trailing content, and swipe actions.',
    symbols: [
      'VListTile',
      'VSwipeActions',
      'VSwipeActionSide',
      'VSwipeActionBehavior',
    ],
    snippetIds: ['list-tile-basic'],
    usageNotes: [
      'Compose VListTile with VDivider and VSwipeActions for inbox-style lists.',
    ],
  ),
  VDocPageMetadata(
    slug: 'accordion',
    category: 'Layout',
    title: 'Accordion',
    zhTitle: '手风琴',
    summary:
        'Collapsible sections with animated height transitions and rotating toggle indicators. Supports exclusive single-expand or multi-expand modes.',
    symbols: [
      'VCollapsible',
      'VAccordion',
      'VAccordionItem',
      'VAccordionTheme',
      'VAccordionTokens',
    ],
    snippetIds: ['accordion-collapsible', 'accordion-exclusive', 'accordion-multi'],
    usageNotes: [
      'Use VCollapsible for a single expandable section with header and body.',
      'Use VAccordion to group multiple VAccordionItems with a shared expansion policy.',
      'Set multiple: false for exclusive accordion — opening one section auto-collapses others.',
      'Set multiple: true to allow any number of sections to be open simultaneously.',
      'VCollapsible and VAccordionItem both support controlled (expanded + onChanged) and uncontrolled (initiallyExpanded) state.',
      'Enter and Space toggle the focused section; the chevron indicator rotates smoothly on expand/collapse.',
      'Use VAccordionTheme.override to restyle only the accordion tokens in a subtree.',
    ],
  ),
  VDocPageMetadata(
    slug: 'table',
    category: 'Data',
    title: 'Table',
    zhTitle: '表格',
    summary:
        'Small data tables with explicit columns, widths, and sortable presentation.',
    symbols: ['VTable', 'VTableColumn', 'VTableTheme', 'VTableTokens'],
    snippetIds: ['table-basic', 'table-tokens'],
    usageNotes: [
      'Use concise row values; complex cells should be promoted to a richer data view.',
      'Sortable headers can be clicked or activated with Enter and Space when focused.',
      'Empty tables expose a semantic "No data" state for assistive technology.',
      'VTable is a simple sortable table, not a full data-grid with cell-level keyboard navigation.',
    ],
  ),
  VDocPageMetadata(
    slug: 'tabs',
    category: 'Navigation',
    title: 'Tabs',
    zhTitle: '标签页',
    summary: 'Tabbed navigation and content switching with a compact tab bar.',
    symbols: ['VTabBar', 'VTabItem', 'VTabs'],
    snippetIds: ['tabs-basic'],
    usageNotes: [
      'Keep tab labels short and align children order with the tabs list.',
    ],
  ),
  VDocPageMetadata(
    slug: 'number-box',
    category: 'Forms',
    title: 'Number Box',
    zhTitle: '数字步进器',
    summary:
        'Compact stepper with tap, long-press acceleration, haptic feedback, and keyboard support.',
    symbols: ['VNumberBox', 'VControlSize'],
    snippetIds: [],
    usageNotes: [
      'Long-press for continuous stepping with acceleration.',
      'Arrow keys ↑/↓ step when focused.',
      'Mobile devices get haptic feedback on each step.',
    ],
  ),
  VDocPageMetadata(
    slug: 'navigation-bar',
    category: 'Navigation',
    title: 'Navigation Bar',
    zhTitle: '导航栏',
    summary:
        'Bottom navigation bar with multiple shapes (flat/floating/capsule), indicator styles (pill/dot/topline/none), content modes, and optional center FAB with notch.',
    symbols: [
      'VNavigationBar',
      'VNavigationDestination',
      'VNavigationBarShape',
      'VNavigationBarIndicator',
      'VNavigationBarContentMode',
      'VNavigationBarAnimation',
      'VNavigationBarTheme',
      'VNavigationBarTokens',
    ],
    snippetIds: ['navigation-bar-basic', 'navigation-bar-center-fab'],
    usageNotes: [
      'Use VNavigationBar as VScaffold.footer for standard bottom navigation.',
      'Choose VNavigationBarShape.flat for attached bars, .floating for elevated rounded bars, or .capsule for fully rounded pills.',
      'Choose VNavigationBarIndicator.pill for a sliding pill, .dot for a minimal dot, .topLine for a top accent line, or .none for color-only feedback.',
      'Use VNavigationBarContentMode.iconsOnly for compact icon-only bars, or .labelsOnly for text tabs.',
      'Choose VNavigationBarAnimation.scale for bouncy icon scaling, .shift for sliding text fades, or .none for instant transitions.',
      'Pass centerDestination to add a raised circular FAB with a notched bar cutout.',
      'Pass VBadge(count: n) or VBadge(showDot: true) to individual destinations for notification indicators.',
      'Use VNavigationBarTheme.override to customize tokens for a subtree.',
    ],
  ),
  VDocPageMetadata(
    slug: 'pagination',
    category: 'Navigation',
    title: 'Pagination',
    zhTitle: '分页',
    summary:
        'Page-navigation control with automatic ellipsis using the industry-standard boundaryCount + siblingCount algorithm.',
    symbols: ['VPagination', 'VPageItem', 'VPageNumber', 'VPageEllipsis'],
    snippetIds: [],
    usageNotes: [
      'VPagination is a pure navigation control — it emits onPageChanged and never fetches data itself.',
      'Use boundaryCount and siblingCount to control how many slots are visible around the current page.',
      'Pass disabled: true when a new page is loading to prevent rapid duplicate navigation.',
    ],
  ),
  VDocPageMetadata(
    slug: 'overlay',
    category: 'Overlay',
    title: 'Overlay',
    zhTitle: '浮层',
    summary:
        'Toast and dialog APIs powered by VOverlayHost instead of ScaffoldMessenger or showDialog.',
    symbols: [
      'VToast',
      'VToastHandle',
      'VToastStackMode',
      'VToastTheme',
      'VToastTokens',
      'VToastVariant',
      'VToastPosition',
      'VToastActionBuilder',
      'VAlertDialog',
      'VDialog',
      'VDialogTheme',
      'VDialogSurface',
      'VDialogScope',
      'VDialogTokens',
      'VOverlayHost',
      'VOverlayHostState',
      'VOverlayController',
      'VOverlayHandle',
      'VOverlayControllerScope',
      'VOverlayEntryBuilder',
      'VOverlayAnimation',
      'VOverlayBarrierMode',
      'VOverlayPresentation',
      'VOverlayPresenter',
      'VOverlayPresenterConfig',
      'VPopover',
      'VPopoverContentBuilder',
      'VPopoverController',
      'VPopoverTriggerBuilder',
      'VAnchoredOverlayGeometry',
      'VAnchoredOverlayPlacement',
      'VOverlay',
      'VTooltip',
    ],
    snippetIds: ['overlay-basic', 'dialog-basic'],
    usageNotes: [
      'Call overlay APIs with a context below VidraApp so VOverlayHost is available.',
      'Use VDialogScope.of inside dialog builders to close with a typed result.',
      'Use VDialogSurface for route semantics and tokenized dialog shape.',
      'Use surfaceBackground on VDialog, VSheet, and VPopover when a one-off overlay surface background is needed; it does not affect barriers or anchors.',
      'Use toast for transient feedback and dialog only when the user must make or acknowledge a decision.',
    ],
  ),
  VDocPageMetadata(
    slug: 'sheet',
    category: 'Overlay',
    title: 'Sheet',
    zhTitle: '边缘面板',
    summary:
        'Modal edge sheets and scaffold-participating bottom sheets with tokenized motion and keyboard behavior.',
    symbols: [
      'VSheet',
      'VSheetSurface',
      'VSheetScope',
      'VSheetEdge',
      'VSheetKeyboardBehavior',
      'VSheetSize',
    ],
    snippetIds: ['sheet-basic'],
    usageNotes: [
      'Use VSheet.show for modal edge sheets and VScaffold.bottomSheet for pushed bottom layout. Pass edge: VSheetEdge.bottom for bottom sheets.',
    ],
  ),
  VDocPageMetadata(
    slug: 'motion',
    category: 'Motion',
    title: 'Motion',
    zhTitle: '动效',
    summary:
        'Motion tokens, scoped overrides, animated helpers, content switcher, typewriter text, page transitions, and staggered entrance.',
    symbols: [
      'VMotion',
      'VMotionSpec',
      'VMotionScope',
      'VMotionResolver',
      'VPageTransition',
      'VAnimatedText',
      'VAnimatedTextData',
      'VAnimatedTextEffect',
      'VTextAnimationEffect',
      'VAnimatedBox',
      'VAnimatedSwitcher',
      'VAnimatedSwitcherController',
      'VContentTransition',
      'VAnimatedVisibility',
      'VAnimatedScaleFade',
      'VAnimatedSlideFade',
      'VStagger',
      'VAnimatedList',
      'VScrollableList',
      'VScrollableListController',
      'VScrollableListItemBuilder',
      'VScrollableListRefreshBuilder',
      'VScrollableListScrollButtonBuilder',
      'VScrollableListSeparatorBuilder',
      'VScrollableGrid',
      'VGridLayout',
      'VGridItemBuilder',
      'VTypewriterText',
      'VTypewriterMode',
    ],
    snippetIds: ['motion-basic', 'scrollable-list-basic'],
    usageNotes: [
      'Use VMotionScope for subtree overrides such as reduced motion.',
      'Prefer the animated helpers before writing custom animation controllers.',
      'Use VTypewriterText for letter-by-letter typing or soft opacity reveal effects driven by VMotion tokens.',
      'VTypewriterText streaming mode: appending to text continues typing from the new suffix without restarting.',
    ],
  ),
  VDocPageMetadata(
    slug: 'media',
    category: 'Media',
    title: 'Media',
    zhTitle: '媒体',
    summary: 'Icons, avatar, image sources, and image loading primitives.',
    symbols: [
      'VIcon',
      'VIconTheme',
      'VIconThemeData',
      'VAvatar',
      'VControlSize',
      'VImage',
      'VImageCache',
      'VImageSource',
      'VNetworkImageSource',
      'VAssetImageSource',
      'VMemoryImageSource',
    ],
    snippetIds: ['media-basic'],
    usageNotes: [
      'Provide semanticLabel for meaningful icons and images.',
      'Use VImageSource subclasses when image source type is decided outside the widget.',
    ],
  ),
  VDocPageMetadata(
    slug: 'feedback',
    category: 'Feedback',
    title: 'Feedback',
    zhTitle: '反馈',
    summary:
        'Progress, spinner, badge, divider, skeleton, steps, and timeline indicators.',
    symbols: [
      'VEmptyState',
      'VProgressBar',
      'VSpinner',
      'VBadge',
      'VDivider',
      'VDividerStyle',
      'VDividerTheme',
      'VDividerTokens',
      'VSkeletonBox',
      'VSkeletonCircle',
      'VShimmer',
      'VSteps',
      'VStep',
      'VStepsMode',
      'VTimeLine',
      'VTimeLineItem',
      'VTimeLineStatus',
    ],
    snippetIds: ['feedback-basic'],
    usageNotes: [
      'Use null progress values for indeterminate progress.',
      'Use skeletons to reserve layout while content is loading.',
      'Use VSteps for step-by-step progress (horizontal or vertical, dot or number).',
      'Use VTimeLine for chronological event sequences with status nodes.',
    ],
  ),
  VDocPageMetadata(
    slug: 'carousel',
    category: 'Media',
    title: 'Carousel',
    zhTitle: '轮播',
    summary: 'A compact carousel for swipeable or stepwise feature panels.',
    symbols: ['VCarousel'],
    snippetIds: ['carousel-basic'],
    usageNotes: [
      'Give slides stable dimensions so the carousel does not jump between pages.',
    ],
  ),
  VDocPageMetadata(
    slug: 'appearance',
    category: 'Theme',
    title: 'Appearance',
    zhTitle: '外观',
    summary:
        'Generic appearance hooks and scoped styling without trend-specific core APIs.',
    symbols: [
      'VAppearance',
      'VFlatAppearance',
      'VSoftAppearance',
      'VOutlinedAppearance',
      'VAppearanceScope',
      'VVisualBox',
      'VInnerShadowPainter',
    ],
    snippetIds: ['appearance-basic'],
    usageNotes: [
      'Keep opinionated styles in example or app code, not VidraUI core.',
      'Use VAppearanceScope to change a subtree instead of adding per-component flags.',
    ],
  ),
  VDocPageMetadata(
    slug: 'theme',
    category: 'Theme',
    title: 'Theme',
    zhTitle: '主题',
    summary:
        'Theme data, animated theme transitions, locale labels, component tokens, and scoped overrides.',
    symbols: [
      'VTheme',
      'VThemeData',
      'VThemeDataTween',
      'VThemeTokenOverride',
      'VScopedTokenOverride',
      'VComponentTokensOverride',
      'VAnimatedTheme',
      'VThemeMode',
      'VTokenTheme',
      'VComponentThemeWrapper',
      'VComponentTokens',
      'VStateProperty',
      'VButtonTheme',
      'VButtonTokensOverride',
      'VChipTheme',
      'VLocale',
      'VLocaleStrings',
    ],
    snippetIds: [
      'theme-basic',
      'theme-component-override',
      'theme-token-override',
    ],
    usageNotes: [
      'Use VTheme.of(context) to read tokens in app code.',
      'Use VTheme.override for scoped semantic token changes; component tokens are regenerated from overridden colors by default.',
      'Use component theme wrappers such as VButtonTheme.override, VSelectTheme.override, and VInputTheme.override when only one component family should change.',
      'Use VTokenTheme<T> directly for advanced token scopes; named component wrappers are thin typed aliases over it.',
      'Prefer semantic token overrides over primitive color references in app widgets.',
      'Keep local theme overrides narrow so unrelated components continue to inherit the application theme.',
    ],
  ),
  VDocPageMetadata(
    slug: 'tokens',
    category: 'Foundation',
    title: 'Tokens',
    zhTitle: '设计令牌',
    summary:
        'Primitive, semantic, spacing, radii, shadow, state, responsive, and adaptive platform tokens.',
    symbols: [
      'VPrimitiveColors',
      'VColors',
      'VSpacing',
      'VRadii',
      'VShadows',
      'VStateProperty',
      'VBreakpoint',
      'VBreakpointValues',
      'VPlatformBehavior',
      'VPlatformScope',
      'VGestureDetector',
    ],
    snippetIds: ['tokens-basic', 'state-property-basic'],
    usageNotes: [
      'Widgets should consume semantic/component tokens, not primitive colors.',
      'Every visual token that participates in theme animation should have lerp support.',
      'Use VStateProperty when a value changes across disabled, error, pressed, hovered, focused, selected, and normal states.',
      'When app code needs spacing, radii, typography, or motion, read it from VTheme.of(context) instead of repeating literals.',
    ],
  ),
  VDocPageMetadata(
    slug: 'responsive',
    category: 'Foundation',
    title: 'Responsive',
    zhTitle: '响应式',
    summary:
        'Screen metrics, breakpoints, keyboard insets, and responsive value selection.',
    symbols: ['VResponsive'],
    snippetIds: ['responsive-basic'],
    usageNotes: [
      'Use context breakpoint extensions for layout decisions near the widget that owns layout.',
    ],
  ),
  VDocPageMetadata(
    slug: 'app-shell',
    category: 'Application',
    title: 'App Shell',
    zhTitle: '应用壳',
    summary:
        'WidgetsApp-based application shell, routing adapters, scroll behavior, and page route transitions.',
    symbols: [
      'VidraApp',
      'VPageRoute',
      'VRouteAdapter',
      'VNavigatorAdapter',
      'VRouterConfigAdapter',
      'VScrollBehavior',
    ],
    snippetIds: ['app-shell-basic'],
    usageNotes: [
      'Use VidraApp.navigator or VidraApp.router instead of MaterialApp/CupertinoApp.',
      'Keep app shortcuts/actions on WidgetsApp through VidraApp parameters.',
    ],
  ),
  VDocPageMetadata(
    slug: 'page-transitions',
    category: 'Navigation',
    title: 'Page Transitions',
    zhTitle: '页面转场',
    summary:
        'Custom page transition animations for VPageRoute: iOS depth slide, shared axis (X/Y/Z), zoom-up reveal, 3D perspective, fade, adaptive, and none. Includes swipe-to-back gesture for iOS-style routes.',
    symbols: [
      'VPageRoute',
      'VPageTransition',
      'VBackGestureDetector',
      'VBackGestureScope',
    ],
    snippetIds: ['page-transitions-basic'],
    usageNotes: [
      'Set VMotion.pageTransition to choose the app-wide default transition.',
      'Use VMotionScope to override the transition for a specific subtree or screen.',
      'iosDepthSlide and adaptive (on iOS/macOS) automatically enable swipe-to-back from the left 20 px edge — no extra code needed.',
      'VPageRoute accepts any VMotion, so you can combine custom durations/curves with any transition type.',
      'perspective3D applies a Matrix4 Y-axis flip with a 0.001 perspective entry — use sparingly for emphasis screens.',
      'adaptive resolves to iosDepthSlide on iOS/macOS and zoomUpReveal on other platforms at runtime.',
      'none is useful for instant screen replacements such as auth flows or tab switches where animation would feel disorienting.',
    ],
  ),
  VDocPageMetadata(
    slug: 'scroll-area',
    category: 'Layout',
    title: 'Scroll Area',
    zhTitle: '滚动容器',
    summary:
        'A custom scrollable container that integrates VScrollbar and clamped overscroll behavior.',
    symbols: [
      'VScrollArea',
      'VScrollbar',
      'VScrollbarTokens',
      'VWidgetScrollExtension',
    ],
    snippetIds: ['scroll-area-basic'],
    usageNotes: [
      'Use VScrollArea instead of wrapping Columns directly in SingleChildScrollView to automatically apply the clamping VScrollBehavior.',
      'To completely hide the scrollbar, set showScrollbar to false.',
      'Use the scrollable() extension on any Widget for a clean fluent API.',
      'Customize scrollbar thickness, radius, and thumb colors via VThemeData.components.scrollbar.',
    ],
  ),
  VDocPageMetadata(
    slug: 'auto-suggest',
    category: 'Forms',
    title: 'Auto Suggest Box',
    zhTitle: '自动补全输入',
    summary:
        'A combobox that combines VTextField with an anchored suggestion dropdown. Supports sync/async sources, keyboard navigation, match highlighting, and full accessibility.',
    symbols: [
      'VAutoSuggestBox',
      'VAutoSuggestItem',
      'VAutoSuggestBuilder',
      'VAutoSuggestAsyncBuilder',
      'VAutoSuggestTokens',
    ],
    snippetIds: ['auto-suggest-basic'],
    usageNotes: [
      'Provides both synchronous and asynchronous suggestion builders with built-in debouncing.',
      'Supports arrow key navigation (Up/Down) to highlight suggestions, Enter to select, and Escape to close.',
      'Automatically highlights matching substrings in suggested labels if highlightMatch is enabled.',
      'Fully respects accessibility semantics (combobox, active-descendant, and button/item accessibility).',
    ],
  ),
  VDocPageMetadata(
    slug: 'teaching-tip',
    category: 'Overlay',
    title: 'Teaching Tip',
    zhTitle: '新手引导气泡',
    summary:
        'A premium, contextual pop-up tip pointing directly to a target widget to guide users through workflows or feature discoverability.',
    symbols: [
      'VTeachingTip',
      'VTeachingTipTokens',
      'VTeachingTipArrowDirection',
      'VTeachingTipTransitionStyle',
    ],
    snippetIds: ['teaching-tip-basic'],
    usageNotes: [
      'Use VTeachingTip to draw attention to specific UI elements or guide users through a multi-step tour.',
      'Control visibility programmatically using VPopoverController.',
      'Pass a primaryButton or secondaryButton to let users progress or skip the tip.',
      'Supports auto, up, down, left, and right placements with a customizable triangle arrow that visually continuous with the bubble.',
    ],
  ),
];

